#ifndef _TISP_CONFIG_H
#define _TISP_CONFIG_H
	
#define MAX_ATOM_STR_SIZE 16
#define MAX_FUN_PARAMS 5
#define MAX_FUN_RECURSION 4 
#define MAX_TREE_ELEMENTS 625 // Should be MAX_FUN_PARAMS raised to MAX_FUN_RECURSION
#define MAX_FUN_LABEL_STR_SIZE MAX_ATOM_STR_SIZE

#endif//_TISP_CONFIG_H_
