#ifndef _TISP_CONFIG_H
#define _TISP_CONFIG_H

#define MAX_ATOM_STR_SIZE 16
#define MAX_FUN_PARAMS 4
#define MAX_FUN_RECURSION 4
#define MAX_TREE_ELEMENTS 256//MAX_FUN_PARAMS^MAX_FUN_RECURSION


#endif//_TISP_CONFIG_H_



